package org.mingy.lunjian;

import java.util.HashMap;
import java.util.Map;
import java.util.TimerTask;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class AutoQuestionTask extends TimerTask {

	private static final Pattern TITLE_PATTERN = Pattern
			.compile("知识问答第\\s*(\\d+)\\s*/\\s*(\\d+)\\s*题");

	private static final Map<String, String> QUESTIONS = new HashMap<String, String>();

	private CommandLine cmdline;

	static {
		QUESTIONS.put("锦缎腰带是腰带类的第几级装备", "a");
		QUESTIONS.put("扬州询问黑狗子能到下面哪个地点", "a");
		QUESTIONS.put("跨服天剑谷每周六几点开启", "a");
		QUESTIONS.put("论剑中以下哪个不是晚月庄的技能", "d");
		QUESTIONS.put("跨服天剑谷是星期几举行的", "b");
		QUESTIONS.put("玉女剑法是哪个门派的技能", "b");
		QUESTIONS.put("玉草帽可以在哪位npc那里获得", "b");
		QUESTIONS.put("逍遥林是第几章的地图", "c");
		QUESTIONS.put("精铁棒可以在哪位npc那里获得", "d");
		QUESTIONS.put("鎏金缦罗是披风类的第几级装备", "d");
		QUESTIONS.put("神雕大侠在哪一章", "a");
		QUESTIONS.put("华山武器库从哪个NPC进", "d");
		QUESTIONS.put("首冲重置卡需要隔多少天才能在每日充值奖励中领取", "b");
		QUESTIONS.put("以下哪个不是空空儿教导的武学", "b");
		QUESTIONS.put("“迎梅客栈”场景是在哪个地图上", "d");
		QUESTIONS.put("独孤求败有过几把剑", "d");
		QUESTIONS.put("晚月庄的小贩在下面哪个地点", "a");
		QUESTIONS.put("扬州询问黑狗能到下面哪个地点", "a");
		QUESTIONS.put("“清音居”场景是在哪个地图上", "a");
		QUESTIONS.put("一天能完成师门任务有多少个", "c");
		QUESTIONS.put("林祖师是哪个门派的师傅", "a");
		QUESTIONS.put("九区服务器名称", "d");
		QUESTIONS.put("去唐门地下通道要找谁拿钥匙", "a");
		QUESTIONS.put("能增容貌的是下面哪个技能", "a");
		QUESTIONS.put("铁手镯  可以在哪位npc那里获得", "a");
		QUESTIONS.put("街头卖艺是挂机里的第几个任务", "a");
		QUESTIONS.put("“三清宫”场景是在哪个地图上", "c");
		QUESTIONS.put("论剑中以下哪个是大理段家的技能", "a");
		QUESTIONS.put("藏宝图在哪里npc那里买", "a");
		QUESTIONS.put("六脉神剑是哪个门派的绝学", "a");
		QUESTIONS.put("如何将华山剑法从400级提升到440级", "d");
		QUESTIONS.put("王重阳是哪个门派的师傅", "b");
		QUESTIONS.put("在庙祝处洗杀气每次可以消除多少点", "a");
		QUESTIONS.put("以下哪个宝石不能镶嵌到衣服", "a");
		QUESTIONS.put("达摩杖的伤害是多少", "d");
		QUESTIONS.put("嫁衣神功是哪个门派的技能", "b");
		QUESTIONS.put("可以召唤金甲伏兵助战是哪个门派", "a");
		QUESTIONS.put("端茶递水是挂机里的第几个任务", "b");
		QUESTIONS.put("下列哪项战斗不能多个玩家一起战斗", "a");
		QUESTIONS.put("寒玉床在哪里切割", "a");
		QUESTIONS.put("拜师风老前辈需要正气多少", "b");
		QUESTIONS.put("每天微信分享能获得多少元宝", "d");
		QUESTIONS.put("丐帮的绝学是什么", "a");
		QUESTIONS.put("以下哪个门派不是隐藏门派", "c");
		QUESTIONS.put("玩家想修改名字可以寻找哪个NPC", "a");
		QUESTIONS.put("论剑中以下哪个不是古墓派的的技能", "b");
		QUESTIONS.put("安惜迩是在那个场景", "c");
		QUESTIONS.put("神雕侠侣的时代背景是哪个朝代", "d");
		QUESTIONS.put("论剑中以下哪个是华山派的技能的", "a");
		QUESTIONS.put("夜皇在大旗门哪个场景", "c");
		QUESTIONS.put("什么装备可以镶嵌紫水晶", "c");
		QUESTIONS.put("乌檀木刀可以在哪位npc那里获得", "d");
		QUESTIONS.put("易容后保持时间是多久", "a");
		QUESTIONS.put("以下哪个不是宋首侠教导的武学", "d");
		QUESTIONS.put("踏云棍可以在哪位npc那里获得", "a");
		QUESTIONS.put("玉女剑法是哪个门派的技能", "b");
		QUESTIONS.put("根骨能提升哪个属性", "c");
		QUESTIONS.put("论剑中以下哪个是铁血大旗门的技能", "b");
		QUESTIONS.put("明教的九阳神功有哪个特殊效果", "a");
		QUESTIONS.put("辟邪剑法在哪学习", "b");
		QUESTIONS.put("论剑中古墓派的终极师傅是谁", "d");
		QUESTIONS.put("论剑中青城派的终极师傅是谁", "d");
		QUESTIONS.put("逍遥林怎么弹琴可以见到天山姥姥", "b");
		QUESTIONS.put("论剑一次最多能突破几个技能", "c");
		QUESTIONS.put("劈雳拳套有几个镶孔", "a");
		QUESTIONS.put("仓库最多可以容纳多少种物品", "b");
		QUESTIONS.put("以下不是天宿派师傅的是哪个", "c");
		QUESTIONS.put("易容术在哪学习", "b");
		QUESTIONS.put("瑷伦在晚月庄的哪个场景", "b");
		QUESTIONS.put("羊毛斗篷是披风类的第几级装备", "a");
		QUESTIONS.put("弯月刀可以在哪位npc那里获得", "b");
		QUESTIONS.put("骆云舟在乔阴县的哪个场景", "b");
		QUESTIONS.put("屠龙刀是什么级别的武器", "a");
		QUESTIONS.put("天蚕围腰可以镶嵌几颗宝石", "d");
		QUESTIONS.put("“蓉香榭”场景是在哪个地图上", "c");
		QUESTIONS.put("施令威在哪个地图", "b");
		QUESTIONS.put("扬州在下面哪个地点的npc处可以获得玉佩", "c");
		QUESTIONS.put("拜师铁翼需要多少内力", "b");
		QUESTIONS.put("九区服务器名称", "d");
		QUESTIONS.put("\"白玉牌楼\"场景是在哪个地图上", "c");
		QUESTIONS.put("宝玉鞋在哪获得", "a");
		QUESTIONS.put("落英神剑掌是哪个门派的技能", "b");
		QUESTIONS.put("下面哪个门派是正派", "a");
		QUESTIONS.put("兑换易容面具需要多少玄铁碎片", "c");
		QUESTIONS.put("以下哪些物品是成长计划第五天可以领取的", "b");
		QUESTIONS.put("论剑中以下哪个是晚月庄的人物", "a");
		QUESTIONS.put("论剑中以下哪个不是魔教的技能", "a");
		QUESTIONS.put("匕首加什么属性", "c");
		QUESTIONS.put("钢丝甲衣可以在哪位npc那里获得", "d");
		QUESTIONS.put("论剑中花紫会的师傅是谁", "c");
		QUESTIONS.put("暴雨梨花针的伤害是多少", "c");
		QUESTIONS.put("吸血蝙蝠在下面哪个地图", "a");
		QUESTIONS.put("论剑中以下是峨嵋派技能的是哪个", "a");
		QUESTIONS.put("蓝止萍在晚月庄哪个小地图", "b");
		QUESTIONS.put("下面哪个地点不是乔阴县的", "d");
		QUESTIONS.put("领取消费积分需要寻找哪个NPC", "c");
		QUESTIONS.put("下面哪个不是门派绝学", "d");
		QUESTIONS.put("人物背包最多可以容纳多少种物品", "a");
		QUESTIONS.put("什么装备不能镶嵌黄水晶", "d");
		QUESTIONS.put("古灯大师在大理哪个场景", "c");
		QUESTIONS.put("草帽可以在哪位npc那里获得", "b");
		QUESTIONS.put("西毒蛇杖的伤害是多少", "c");
		QUESTIONS.put("成长计划六天可以领取多少银两", "d");
		QUESTIONS.put("朱老伯在华山村哪个小地图", "b");
		QUESTIONS.put("论剑中以下哪个是唐门的技能", "b");
		QUESTIONS.put("游龙散花是哪个门派的阵法", "d");
		QUESTIONS.put("高级乾坤再造丹加什么", "b");
		QUESTIONS.put("唐门的唐门毒经有哪个特殊效果", "a");
		QUESTIONS.put("葛伦在大招寺的哪个场景", "b");
		QUESTIONS.put("“三清殿”场景是在哪个地图上", "b");
		QUESTIONS.put("哪样不能获得玄铁碎片", "c");
		QUESTIONS.put("在哪里捏脸提升容貌", "d");
		QUESTIONS.put("论剑中以下哪个是天邪派的技能", "b");
		QUESTIONS.put("向师傅磕头可以获得什么", "b");
		QUESTIONS.put("骆云舟在哪一章", "c");
		QUESTIONS.put("论剑中以下哪个不是唐门的技能", "c");
		QUESTIONS.put("华山村王老二掉落的物品是什么", "a");
		QUESTIONS.put("下面有什么是寻宝不能获得的", "c");
		QUESTIONS.put("寒玉床需要切割多少次", "d");
		QUESTIONS.put("绿宝石加什么属性", "c");
		QUESTIONS.put("魏无极处读书可以读到多少级", "a");
		QUESTIONS.put("天山姥姥在逍遥林的哪个场景", "d");
		QUESTIONS.put("天羽奇剑是哪个门派的技能", "a");
		QUESTIONS.put("大招寺的铁布衫有哪个特殊效果", "c");
		QUESTIONS.put("挖剑冢可得什么", "a");
		QUESTIONS.put("灭绝师太在峨眉山哪个场景", "a");
		QUESTIONS.put("论剑是星期几举行的", "c");
		QUESTIONS.put("柳淳风在雪亭镇哪个场景", "b");
		QUESTIONS.put("萧辟尘在哪一章", "d");
		QUESTIONS.put("论剑中以下哪个是明教的技能", "b");
		QUESTIONS.put("天邪派在哪里拜师", "b");
		QUESTIONS.put("钨金腰带是腰带类的第几级装备", "d");
		QUESTIONS.put("灭绝师太在第几章", "c");
		QUESTIONS.put("一指弹在哪里领悟", "b");
		QUESTIONS.put("翻译梵文一次多少银两", "d");
		QUESTIONS.put("刀法基础在哪掉落", "a");
		QUESTIONS.put("黯然消魂掌有多少招式", "c");
		QUESTIONS.put("黑狗血在哪获得", "b");
		QUESTIONS.put("雪蕊儿在铁雪山庄的哪个场景", "d");
		QUESTIONS.put("东方教主在魔教的哪个场景", "b");
		QUESTIONS.put("以下属于正派的门派是哪个", "a");
		QUESTIONS.put("选择武学世家会影响哪个属性", "a");
		QUESTIONS.put("寒玉床睡觉一次多久", "c");
		QUESTIONS.put("魏无极在第几章", "a");
		QUESTIONS.put("孙天灭是哪个门派的师傅", "c");
		QUESTIONS.put("易容术在哪里学习", "a");
		QUESTIONS.put("哪个NPC掉落拆招基础", "a");
		QUESTIONS.put("七星剑法是哪个门派的绝学", "a");
		QUESTIONS.put("以下哪些物品不是成长计划第二天可以领取的", "c");
		QUESTIONS.put("以下哪个门派是中立门派", "a");
		QUESTIONS.put("黄袍老道是哪个门派的师傅", "c");
		QUESTIONS.put("舞中之武是哪个门派的阵法", "b");
		QUESTIONS.put("隐者之术是那个门派的阵法", "a");
		QUESTIONS.put("踏雪无痕是哪个门派的技能", "b");
		QUESTIONS.put("以下哪个不是在雪亭镇场景", "d");
		QUESTIONS.put("排行榜最多可以显示多少名玩家", "a");
		QUESTIONS.put("貂皮斗篷是披风类的第几级装备", "b");
		QUESTIONS.put("武当派的绝学技能是以下哪个", "d");
		QUESTIONS.put("兰花拂穴手是哪个门派的技能", "a");
		QUESTIONS.put("油流麻香手是哪个门派的技能", "a");
		QUESTIONS.put("清风寨在哪", "b");
		QUESTIONS.put("披星戴月是披风类的第几级装备", "d");
		QUESTIONS.put("当日最低累积充值多少元即可获得返利", "b");
		QUESTIONS.put("追风棍在哪里获得", "b");
		QUESTIONS.put("长剑在哪里可以购买", "a");
		QUESTIONS.put("莫不收在哪一章", "a");
		QUESTIONS.put("读书写字最高可以到多少级", "b");
		QUESTIONS.put("哪个门派拜师没有性别要求", "d");
		QUESTIONS.put("墨磷腰带是腰带类的第几级装备", "d");
		QUESTIONS.put("不属于白驼山的技能是什么", "b");
		QUESTIONS.put("婆萝蜜多心经是哪个门派的技能", "b");
		QUESTIONS.put("乾坤一阳指是哪个师傅教的", "a");
		QUESTIONS.put("“日月洞”场景是在哪个地图上", "b");
		QUESTIONS.put("倚天屠龙记的时代背景哪个朝代", "a");
		QUESTIONS.put("八卦迷阵是哪个门派的阵法", "b");
		QUESTIONS.put("七宝天岚舞是哪个门派的技能", "d");
		QUESTIONS.put("断云斧是哪个门派的技能", "a");
		QUESTIONS.put("跨服需要多少级才能进入", "c");
		QUESTIONS.put("易容面具需要多少玄铁兑换", "c");
		QUESTIONS.put("张教主在明教哪个场景", "d");
		QUESTIONS.put("玉蜂浆在哪个地图获得", "a");
		QUESTIONS.put("在逍遥派能学到的技能是哪个", "a");
		QUESTIONS.put("每日微信分享可以获得什么奖励", "a");
		QUESTIONS.put("红宝石加什么属性", "b");
		QUESTIONS.put("金玉断云是哪个门派的阵法", "a");
		QUESTIONS.put("正邪任务一天能做几次", "a");
		QUESTIONS.put("白金戒指可以在哪位npc那里获得", "b");
		QUESTIONS.put("金戒指可以在哪位npc那里获得", "d");
		QUESTIONS.put("柳淳风在哪哪一章", "c");
		QUESTIONS.put("论剑是什么时间点正式开始", "a");
		QUESTIONS.put("黯然销魂掌是哪个门派的技能", "a");
		QUESTIONS.put("在正邪任务中不能获得下面什么奖励", "d");
		QUESTIONS.put("孤儿出身增加什么", "d");
		QUESTIONS.put("丁老怪在星宿海的哪个场景", "b");
		QUESTIONS.put("读书写字301-400级在哪里买书", "c");
		QUESTIONS.put("闯楼第几层可以获得称号“藏剑楼长老”", "c");
		QUESTIONS.put("以下属于邪派的门派是哪个", "b");
		QUESTIONS.put("论剑中以下哪个不是丐帮的人物", "a");
		QUESTIONS.put("论剑中青城派的第一个师傅是谁", "a");
		QUESTIONS.put("以下哪个不是何不净教导的武学", "c");
		QUESTIONS.put("吕进在哪个地图", "a");
		QUESTIONS.put("拜师老毒物需要蛤蟆功多少级", "a");
		QUESTIONS.put("蛇形刁手是哪个门派的技能", "b");
		QUESTIONS.put("乌金玄火鞭的伤害是多少", "d");
		QUESTIONS.put("张松溪在哪个地图", "c");
		QUESTIONS.put("欧阳敏是哪个门派的师傅", "b");
		QUESTIONS.put("欧阳敏是哪个门派的", "b");
		QUESTIONS.put("以下哪个门派是正派", "d");
		QUESTIONS.put("成功易容成异性几次可以领取易容成就奖", "b");
		QUESTIONS.put("论剑中以下不是峨嵋派技能的是哪个", "b");
		QUESTIONS.put("城里抓贼是挂机里的第几个任务", "b");
		QUESTIONS.put("每天的任务次数几点重置", "d");
		QUESTIONS.put("莲花掌是哪个门派的技能", "a");
		QUESTIONS.put("大招寺的金刚不坏功有哪个特殊效果", "a");
		QUESTIONS.put("多少消费积分可以换取黄金钥匙", "b");
		QUESTIONS.put("什么装备都能镶嵌的是什么宝石", "c");
		QUESTIONS.put("什么影响打坐的速度", "c");
		QUESTIONS.put("蓝止萍在哪一章", "c");
		QUESTIONS.put("寒玉床睡觉修炼需要多少点内力值", "c");
		QUESTIONS.put("武穆兵法通过什么学习", "a");
		QUESTIONS.put("倒乱七星步法是哪个门派的技能", "d");
		QUESTIONS.put("闯楼第几层可以获得称号“藏剑楼护法”", "b");
		QUESTIONS.put("兽皮鞋可以在哪位npc那里获得", "b");
		QUESTIONS.put("寒玉床在那个地图可以找到", "a");
		QUESTIONS.put("易容术可以找哪位NPC学习", "b");
		QUESTIONS.put("铁戒指可以在哪位npc那里获得", "a");
		QUESTIONS.put("通灵需要寻找哪个NPC", "c");
		QUESTIONS.put("功德箱在雪亭镇的哪个场景", "c");
		QUESTIONS.put("蓝宝石加什么属性", "a");
		QUESTIONS.put("每天分享游戏到哪里可以获得20元宝", "a");
		QUESTIONS.put("选择书香门第会影响哪个属性", "b");
		QUESTIONS.put("以下哪个不是微信分享好友、朋友圈、QQ空间的奖励", "a");
		QUESTIONS.put("新手礼包在哪领取", "c");
		QUESTIONS.put("春风快意刀是哪个门派的技能", "b");
		QUESTIONS.put("朱姑娘是哪个门派的师傅", "a");
		QUESTIONS.put("出生选武学世家增加什么", "a");
		QUESTIONS.put("以下哪个宝石不能镶嵌到内甲", "a");
		QUESTIONS.put("生死符的伤害是多少", "a");
		QUESTIONS.put("扬文的属性", "a");
		QUESTIONS.put("云问天在哪一章", "a");
		QUESTIONS.put("首次通过桥阴县不可以获得那种奖励", "a");
		QUESTIONS.put("剑冢在哪个地图", "a");
		QUESTIONS.put("在哪里消杀气", "a");
		QUESTIONS.put("闯楼每多少层有称号奖励", "a");
		QUESTIONS.put("打坐增长什么属性", "a");
		QUESTIONS.put("从哪个npc处进入跨服战场", "a");
		QUESTIONS.put("下面哪个是天邪派的师傅", "a");
		QUESTIONS.put("每天能做多少个谜题任务", "a");
		QUESTIONS.put("小男孩在华山村哪里", "a");
		QUESTIONS.put("追风棍可以在哪位npc那里获得", "a");
		QUESTIONS.put("逍遥派的绝学技能是以下哪个", "a");
		QUESTIONS.put("沧海护腰是腰带类的第几级装备", "a");
		QUESTIONS.put("花花公子在哪个地图", "a");
		QUESTIONS.put("每次合成宝石需要多少银两", "a");
		QUESTIONS.put("以下哪个不是微信分享好友、朋友圈、QQ空间的奖励", "a");
		QUESTIONS.put("打排行榜每天可以完成多少次", "a");
		QUESTIONS.put("夜行披风是披风类的第几级装备", "a");
		QUESTIONS.put("白蟒鞭的伤害是多少", "a");
		QUESTIONS.put("易容术向谁学习", "a");
		QUESTIONS.put("支线对话书生上魁星阁二楼杀死哪个NPC给10元宝", "a");
		QUESTIONS.put("斗转星移是哪个门派的技能", "a");
		QUESTIONS.put("杨过在哪个地图", "a");
		QUESTIONS.put("钻石项链在哪获得", "a");
		QUESTIONS.put("多少消费积分换取黄金宝箱", "a");
		QUESTIONS.put("每突破一次技能有效系数加多少", "a");
		QUESTIONS.put("茅山学习什么技能招宝宝", "a");
		QUESTIONS.put("陆得财在乔阴县的哪个场景", "a");
		QUESTIONS.put("独龙寨是第几个组队副本", "a");
		QUESTIONS.put("以下哪个是花紫会的祖师", "a");
		QUESTIONS.put("金弹子的伤害是多少", "a");
		QUESTIONS.put("明月帽要多少刻刀摩刻", "a");
		QUESTIONS.put("论剑输一场获得多少论剑积分", "a");
		QUESTIONS.put("论剑中以下哪个是铁血大旗门的师傅", "a");
		QUESTIONS.put("8级的装备摹刻需要几把刻刀", "a");
		QUESTIONS.put("赠送李铁嘴银两能够增加什么", "a");
		QUESTIONS.put("金刚不坏功有什么效果", "a");
		QUESTIONS.put("少林的易筋经神功有哪个特殊效果", "a");
		QUESTIONS.put("大旗门的修养术有哪个特殊效果", "a");
		QUESTIONS.put("金刚杖的伤害是多少", "a");
		QUESTIONS.put("双儿在扬州的哪个小地图", "a");
		QUESTIONS.put("花不为在哪一章", "a");
		QUESTIONS.put("铁项链可以在哪位npc那里获得", "a");
		QUESTIONS.put("武学世家加的什么初始属性", "a");
		QUESTIONS.put("师门磕头增加什么", "a");
		QUESTIONS.put("全真的道家心法有哪个特殊效果", "a");
		QUESTIONS.put("功德箱捐香火钱有什么用", "a");
		QUESTIONS.put("雪莲有什么作用", "a");
		QUESTIONS.put("论剑中以下哪个是花紫会的技能", "a");
		QUESTIONS.put("柳文君所在的位置", "a");
		QUESTIONS.put("岳掌门在哪一章", "a");
		QUESTIONS.put("长虹剑在哪位npc那里获得", "a");
		QUESTIONS.put("副本一次最多可以进几人", "a");
		QUESTIONS.put("师门任务每天可以完成多少次", "a");
		QUESTIONS.put("逍遥步是哪个门派的技能", "a");
		QUESTIONS.put("新人礼包在哪个npc处兑换", "a");
		QUESTIONS.put("使用朱果经验潜能将分别增加多少", "a");
		QUESTIONS.put("欧阳敏在哪一章", "a");
		QUESTIONS.put("辟邪剑法是哪个门派的绝学技能", "a");
		QUESTIONS.put("在哪个npc处可以更改名字", "a");
		QUESTIONS.put("毒龙鞭的伤害是多少", "a");
		QUESTIONS.put("晚月庄主线过关要求", "a");
		QUESTIONS.put("怎么样获得免费元宝", "a");
		QUESTIONS.put("成长计划需要多少元宝方可购买", "a");
		QUESTIONS.put("青城派的道家心法有哪个特殊效果", "a");
		QUESTIONS.put("藏宝图在哪个NPC处购买", "a");
		QUESTIONS.put("丁老怪是哪个门派的终极师傅", "a");
		QUESTIONS.put("斗转星移阵是哪个门派的阵法", "a");
		QUESTIONS.put("挂机增长什么", "a");
		QUESTIONS.put("鹰爪擒拿手是哪个门派的技能", "a");
		QUESTIONS.put("八卦迷阵是那个门派的阵法", "a");
		QUESTIONS.put("一天能完成挑战排行榜任务多少次", "a");
		QUESTIONS.put("论剑每天能打几次", "a");
		QUESTIONS.put("需要使用什么衣服才能睡寒玉床", "a");
		QUESTIONS.put("张天师是哪个门派的师傅", "a");
		QUESTIONS.put("技能柳家拳谁教的", "a");
		QUESTIONS.put("九阴派梅师姐在星宿海哪个场景", "a");
		QUESTIONS.put("哪个npc处可以捏脸", "a");
		QUESTIONS.put("论剑中步玄派的师傅是哪个", "a");
		QUESTIONS.put("宝玉鞋击杀哪个npc可以获得", "a");
		QUESTIONS.put("慕容家主在慕容山庄的哪个场景", "a");
		QUESTIONS.put("闻旗使在哪个地图", "a");
		QUESTIONS.put("虎皮腰带是腰带类的第几级装备", "a");
		QUESTIONS.put("在哪里可以找到“香茶”", "a");
		QUESTIONS.put("打造刻刀需要多少个玄铁", "a");
		QUESTIONS.put("包家将是哪个门派的师傅", "a");
		QUESTIONS.put("论剑中以下哪个是天邪派的人物", "a");
		QUESTIONS.put("升级什么技能可以提升根骨", "a");
		QUESTIONS.put("NPC公平子在哪一章地图", "a");
		QUESTIONS.put("逄义是在那个场景", "a");
		QUESTIONS.put("锻造一把刻刀需要多少银两", "a");
		QUESTIONS.put("以下哪个不是岳掌门教导的武学", "a");
		QUESTIONS.put("捏脸需要寻找哪个NPC", "a");
		QUESTIONS.put("论剑中以下哪个是晚月庄的技能", "a");
		QUESTIONS.put("碧海潮生剑在哪位师傅处学习", "a");
		QUESTIONS.put("干苦力是挂机里的第几个任务", "a");
		QUESTIONS.put("铁血大旗门云海心法可以提升什么", "a");
		QUESTIONS.put("以下哪些物品是成长计划第四天可以领取的", "a");
		QUESTIONS.put("易容术多少级才可以易容成异性NPC", "a");
		QUESTIONS.put("摹刻扬文需要多少把刻刀", "a");
		QUESTIONS.put("正邪任务中客商的在哪个地图", "a");
		QUESTIONS.put("白驼山第一位要拜的师傅是谁", "a");
		QUESTIONS.put("枯荣禅功是哪个门派的技能", "a");
		QUESTIONS.put("漫天花雨匕在哪获得", "a");
		QUESTIONS.put("摧心掌是哪个门派的技能", "a");
		QUESTIONS.put("“花海”场景是在哪个地图上", "a");
		QUESTIONS.put("雪蕊儿是哪个门派的师傅", "a");
		QUESTIONS.put("新手礼包在哪里领取", "a");
		QUESTIONS.put("银丝链甲衣可以在哪位npc那里获得", "a");
		QUESTIONS.put("乾坤大挪移属于什么类型的武功", "a");
		QUESTIONS.put("移开明教石板需要哪项技能到一定级别", "a");
		QUESTIONS.put("开通VIP月卡最低需要当天充值多少元方有购买资格", "a");
		QUESTIONS.put("黯然销魂掌有多少招式", "c");
		QUESTIONS.put("“跪拜坪”场景是在哪个地图上", "b");
		QUESTIONS.put("孤独求败称号需要多少论剑积分兑换", "b");
		QUESTIONS.put("孔雀氅可以镶嵌几颗宝石", "b");
		QUESTIONS.put("客商在哪一章", "b");
		QUESTIONS.put("疯魔杖的伤害是多少", "b");
		QUESTIONS.put("丐帮的轻功是哪个", "b");
		QUESTIONS.put("霹雳掌套的伤害是多少", "b");
		QUESTIONS.put("方媃是哪个门派的师傅", "b");
		QUESTIONS.put("拜师张三丰需要多少正气", "b");
		QUESTIONS.put("天师阵法是哪个门派的阵法", "b");
		QUESTIONS.put("选择商贾会影响哪个属性", "b");
		QUESTIONS.put("银手镯可以在哪位npc那里获得", "b");
		QUESTIONS.put("清风寨在哪个地图", "d");
		QUESTIONS.put("在雪亭镇李火狮可以学习多少级柳家拳", "b");
		QUESTIONS.put("华山施戴子掉落的物品是什么", "b");
		QUESTIONS.put("尹志平是哪个门派的师傅", "b");
		QUESTIONS.put("病维摩拳是哪个门派的技能", "b");
		QUESTIONS.put("茅山的绝学是什么", "b");
		QUESTIONS.put("茅山派的轻功是什么", "b");
		QUESTIONS.put("风泉之剑可以在哪位npc那里获得", "b");
		QUESTIONS.put("凌波微步是哪个门派的技能", "b");
		QUESTIONS.put("藏宝图在哪个npc处购买", "b");
		QUESTIONS.put("军营是第几个组队副本", "b");
		QUESTIONS.put("北岳殿神像后面是哪位npc", "b");
		QUESTIONS.put("王重阳是哪个门派的师傅", "b");
		QUESTIONS.put("跨服是星期几举行的", "b");
		QUESTIONS.put("学习屠龙刀法需要多少内力", "b");
		QUESTIONS.put("高级乾坤再造丹是增加什么的", "b");
		QUESTIONS.put("银项链可以在哪位npc那里获得", "b");
		QUESTIONS.put("每天在线多少个小时即可领取消费积分", "b");
		QUESTIONS.put("晚月庄的内功是什么", "b");
		QUESTIONS.put("冰魄银针的伤害是多少", "b");
		QUESTIONS.put("论剑中以下哪个是丐帮的技能", "b");
		QUESTIONS.put("神雕大侠所在的地图", "b");
		QUESTIONS.put("突破丹在哪里购买", "b");
		QUESTIONS.put("白金手镯可以在哪位npc那里获得", "a");
		QUESTIONS.put("金手镯可以在哪位npc那里获得", "b");
		QUESTIONS.put("以下哪个不是梁师兄教导的武学", "b");
		QUESTIONS.put("技能数量超过了什么消耗潜能会增加", "b");
		QUESTIONS.put("白金项链可以在哪位npc那里获得", "b");
		QUESTIONS.put("小龙女住的古墓是谁建造的", "b");
		QUESTIONS.put("打开引路蜂礼包可以得到多少引路蜂", "b");
		QUESTIONS.put("购买新手进阶礼包在挂机打坐练习上可以享受多少倍收益", "b");
		QUESTIONS.put("白玉腰束是腰带类的第几级装备", "b");
		QUESTIONS.put("老顽童在全真教哪个场景", "b");
		QUESTIONS.put("神雕侠侣的作者是", "b");
		QUESTIONS.put("晚月庄的七宝天岚舞可以提升哪个属性", "b");
		QUESTIONS.put("论剑在周几进行", "b");
		QUESTIONS.put("vip每天不可以领取什么", "b");
		QUESTIONS.put("每天有几次试剑", "b");
		QUESTIONS.put("晚月庄七宝天岚舞可以提升什么", "b");
		QUESTIONS.put("哪个分享可以获得20元宝", "b");
		QUESTIONS.put("大保险卡可以承受多少次死亡后不降技能等级", "b");
		QUESTIONS.put("凌虚锁云步是哪个门派的技能", "b");
		QUESTIONS.put("屠龙刀法是哪个门派的绝学技能", "b");
		QUESTIONS.put("金丝鞋可以在哪位npc那里获得", "b");
		QUESTIONS.put("老毒物在白驮山的哪个场景", "b");
		QUESTIONS.put("毒物阵法是哪个门派的阵法", "b");
		QUESTIONS.put("以下哪个不是知客道长教导的武学", "b");
		QUESTIONS.put("飞仙剑阵是哪个门派的阵法", "b");
		QUESTIONS.put("副本完成后不可获得下列什么物品", "b");
		QUESTIONS.put("晚月庄意寒神功可以提升什么", "b");
		QUESTIONS.put("北冥神功是哪个门派的技能", "b");
		QUESTIONS.put("论剑中以下哪个是青城派的技能", "b");
		QUESTIONS.put("六阴追魂剑是哪个门派的技能", "b");
		QUESTIONS.put("王铁匠是在那个场景", "b");
		QUESTIONS.put("以下哪个是步玄派的祖师", "b");
		QUESTIONS.put("在洛阳萧问天那可以学习什么心法", "b");
		QUESTIONS.put("在哪个npc处能够升级易容术", "b");
		QUESTIONS.put("摹刻10级的装备需要摩刻技巧多少级", "b");
		QUESTIONS.put("师门任务什么时候更新", "b");
		QUESTIONS.put("哪个npc属于全真七子", "b");
		QUESTIONS.put("正邪任务中卖花姑娘在哪个地图", "b");
		QUESTIONS.put("风老前辈在华山哪个场景", "b");
		QUESTIONS.put("“留云馆”场景是在哪个地图上", "b");
		QUESTIONS.put("割鹿刀可以在哪位npc那里获得", "b");
		QUESTIONS.put("论剑中以下哪个是大招寺的技能", "b");
		QUESTIONS.put("全真的基本阵法有哪个特殊效果", "b");
		QUESTIONS.put("论剑要在晚上几点前报名", "b");
		QUESTIONS.put("碧磷鞭的伤害是多少", "b");
		QUESTIONS.put("一天能完成谜题任务多少个", "b");
		QUESTIONS.put("正邪任务杀死好人增长什么", "b");
		QUESTIONS.put("木道人在青城山的哪个场景", "b");
		QUESTIONS.put("论剑中以下哪个不是大招寺的技能", "b");
		QUESTIONS.put("“伊犁”场景是在哪个地图上", "b");
		QUESTIONS.put("“冰火岛”场景是在哪个地图上", "b");
		QUESTIONS.put("“双鹤桥”场景是在哪个地图上", "b");
		QUESTIONS.put("“百龙山庄”场景是在哪个地图上", "b");
		QUESTIONS.put("九阳神功是哪个门派的技能", "c");
		QUESTIONS.put("树王坟在第几章节", "c");
		QUESTIONS.put("阳刚之劲是哪个门派的阵法", "c");
		QUESTIONS.put("上山打猎是挂机里的第几个任务", "c");
		QUESTIONS.put("一张分身卡的有效时间是多久", "c");
		QUESTIONS.put("锻造一把刻刀需要多少玄铁碎片锻造", "c");
		QUESTIONS.put("论剑中以下哪个不是铁血大旗门的技能", "c");
		QUESTIONS.put("如意刀是哪个门派的技能", "c");
		QUESTIONS.put("跨服在哪个场景进入", "c");
		QUESTIONS.put("在哪个NPC可以购买恢复内力的药品", "c");
		QUESTIONS.put("欧阳敏在唐门的哪个场景", "c");
		QUESTIONS.put("密宗伏魔是哪个门派的阵法", "c");
		QUESTIONS.put("孔雀氅是披风类的第几级装备", "c");
		QUESTIONS.put("天山折梅手是哪个门派的技能", "c");
		QUESTIONS.put("玩家每天能够做几次正邪任务", "c");
		QUESTIONS.put("柳淳风在哪一章", "c");
		QUESTIONS.put("茅山天师正道可以提升什么", "c");
		QUESTIONS.put("洪帮主在洛阳哪个场景", "c");
		QUESTIONS.put("以下哪个不是全真七子", "c");
		QUESTIONS.put("云九天是哪个门派的师傅", "c");
		QUESTIONS.put("摹刻烈日宝链需要多少级摩刻技巧", "c");
		QUESTIONS.put("伏虎杖的伤害是多少", "c");
		QUESTIONS.put("灵蛇杖法是哪个门派的技能", "c");
		QUESTIONS.put("“子午楼”场景是在哪个地图上", "c");
		QUESTIONS.put("什么装备可以镶嵌紫水晶", "c");
		QUESTIONS.put("石师妹哪个门派的师傅", "c");
		QUESTIONS.put("烈火旗大厅是那个地图的场景", "c");
		QUESTIONS.put("打土匪是挂机里的第几个任务", "c");
		QUESTIONS.put("捏脸需要花费多少银两", "c");
		QUESTIONS.put("大旗门的云海心法可以提升哪个属性", "c");
		QUESTIONS.put("论剑中以下哪个是铁雪山庄的技能", "c");
		QUESTIONS.put("“白玉牌楼”场景是在哪个地图上", "c");
		QUESTIONS.put("以下哪个宝石不能镶嵌到披风", "c");
		QUESTIONS.put("魏无极身上掉落什么装备", "c");
		QUESTIONS.put("以下不是步玄派的技能的哪个", "c");
		QUESTIONS.put("“常春岛渡口”场景是在哪个地图上", "c");
		QUESTIONS.put("北斗七星阵是第几个的组队副本", "c");
		QUESTIONS.put("宝石合成一次需要消耗多少颗低级宝石", "c");
		QUESTIONS.put("烈日项链可以镶嵌几颗宝石", "c");
		QUESTIONS.put("达摩在少林哪个场景", "c");
		QUESTIONS.put("积分商城在雪亭镇的哪个场景", "c");
		QUESTIONS.put("全真的双手互搏有哪个特殊效果", "c");
		QUESTIONS.put("论剑中以下哪个不是唐门的人物", "c");
		QUESTIONS.put("棋道是哪个门派的技能", "c");
		QUESTIONS.put("七星鞭的伤害是多少", "c");
		QUESTIONS.put("富春茶社在哪一章", "c");
		QUESTIONS.put("等级多少才能在世界频道聊天", "c");
		QUESTIONS.put("以下哪个是封山派的祖师", "c");
		QUESTIONS.put("论剑是星期几进行的", "c");
		QUESTIONS.put("师门任务每天可以做多少个", "c");
		QUESTIONS.put("风泉之剑加几点悟性", "c");
		QUESTIONS.put("黑水伏蛟可以在哪位npc那里获得", "c");
		QUESTIONS.put("陆得财是哪个门派的师傅", "c");
		QUESTIONS.put("拜师小龙女需要容貌多少", "c");
		QUESTIONS.put("下列装备中不可摹刻的是", "c");
		QUESTIONS.put("古灯大师是哪个门派的终极师傅", "c");
		QUESTIONS.put("“翰墨书屋”场景是在哪个地图上", "c");
		QUESTIONS.put("论剑中大招寺第一个要拜的师傅是谁", "c");
		QUESTIONS.put("杨过小龙女分开多少年后重逢", "c");
		QUESTIONS.put("选择孤儿会影响哪个属性", "c");
		QUESTIONS.put("论剑中逍遥派的终极师傅是谁", "c");
		QUESTIONS.put("不可保存装备下线多久会消失", "c");
		QUESTIONS.put("一个队伍最多有几个队员", "c");
//		QUESTIONS.put("论语在哪购买", "c");
		QUESTIONS.put("以下哪个宝石不能镶嵌到戒指", "c");
		QUESTIONS.put("论剑是每周星期几", "c");
		QUESTIONS.put("茅山在哪里拜师", "c");
		QUESTIONS.put("以下哪个宝石不能镶嵌到腰带", "c");
		QUESTIONS.put("黄宝石加什么属性", "c");
		QUESTIONS.put("茅山可以招几个宝宝", "c");
		QUESTIONS.put("唐门密道怎么走", "c");
		QUESTIONS.put("论剑中以下哪个不是大理段家的技能", "c");
		QUESTIONS.put("论剑中以下哪个不是魔教的人物", "d");
		QUESTIONS.put("每天能做多少个师门任务", "c");
		QUESTIONS.put("一天能使用元宝做几次暴击谜题", "c");
		QUESTIONS.put("成长计划第七天可以领取多少元宝", "d");
		QUESTIONS.put("每天能挖几次宝", "d");
		QUESTIONS.put("日月神教大光明心法可以提升什么", "d");
		QUESTIONS.put("在哪个npc处领取免费消费积分", "d");
		QUESTIONS.put("副本有什么奖励", "d");
		QUESTIONS.put("论剑中以下不是华山派的人物的是哪个", "d");
		QUESTIONS.put("论剑中以下哪个不是丐帮的技能", "d");
		QUESTIONS.put("以下哪个不是慧名尊者教导的技能", "d");
		QUESTIONS.put("慕容山庄的斗转星移可以提升哪个属性", "d");
		QUESTIONS.put("论剑中以下哪个不是铁雪山庄的技能", "d");
		QUESTIONS.put("师门任务一天能完成几次", "d");
		QUESTIONS.put("以下有哪些物品不是每日充值的奖励", "d");
		QUESTIONS.put("论剑中以下哪个不是华山派的技能的", "d");
		QUESTIONS.put("武穆兵法提升到多少级才能出现战斗必刷", "d");
		QUESTIONS.put("论剑中以下哪个不是全真教的技能", "d");
		QUESTIONS.put("师门任务最多可以完成多少个", "d");
		QUESTIONS.put("张三丰在哪一章", "d");
		QUESTIONS.put("倚天剑加多少伤害", "d");
		QUESTIONS.put("以下谁不精通降龙十八掌", "d");
		QUESTIONS.put("论剑中以下哪个不是明教的技能", "d");
		QUESTIONS.put("受赠的消费积分在哪里领取", "d");
		QUESTIONS.put("以下哪个不是道尘禅师教导的武学", "d");
		QUESTIONS.put("古墓多少级以后才能进去", "d");
		QUESTIONS.put("千古奇侠称号需要多少论剑积分兑换", "d");
		QUESTIONS.put("魔鞭诀在哪里学习", "d");
		QUESTIONS.put("通灵需要花费多少银两", "d");
		QUESTIONS.put("白银宝箱礼包多少元宝一个", "d");
		QUESTIONS.put("以下哪个不是论剑的皮肤", "d");
		QUESTIONS.put("小李飞刀的伤害是多少", "d");
		QUESTIONS.put("下面哪个npc不是魔教的", "d");
		QUESTIONS.put("天蚕围腰是腰带类的第几级装备", "d");
		QUESTIONS.put("黄岛主在桃花岛的哪个场景", "d");
		QUESTIONS.put("宝玉帽可以在哪位npc那里获得", "d");
		QUESTIONS.put("什么影响攻击力", "d");
		QUESTIONS.put("紫宝石加什么属性", "d");
		QUESTIONS.put("少林的混元一气功有哪个特殊效果", "d");
		QUESTIONS.put("以下哪个是晚月庄的祖师", "d");
		QUESTIONS.put("以下不是隐藏门派的是哪个", "d");
		QUESTIONS.put("第一个副本需要多少等级才能进入", "d");
		QUESTIONS.put("风泉之剑在哪里获得", "d");
		QUESTIONS.put("镖局保镖是挂机里的第几个任务", "d");
		QUESTIONS.put("下面哪个不是古墓的师傅", "d");
		QUESTIONS.put("每个玩家最多能有多少个好友", "b");
		QUESTIONS.put("以下哪个不是在扬州场景", "d");
		QUESTIONS.put("茅山的天师正道可以提升哪个属性", "d");
		QUESTIONS.put("“无名山脚”场景是在哪个地图上", "d");
		QUESTIONS.put("闯楼第几层可以获得称号“藏剑楼楼主”", "d");
		QUESTIONS.put("充值积分不可以兑换下面什么物品", "d");
		QUESTIONS.put("魔教的大光明心法可以提升哪个属性", "d");
		QUESTIONS.put("以下哪些物品不是成长计划第三天可以领取的", "d");
		QUESTIONS.put("论剑中以下哪个不是峨嵋派可以拜师的师傅", "d");
		QUESTIONS.put("哪个技能不是魔教的", "d");
		QUESTIONS.put("沧海护腰可以镶嵌几颗宝石", "d");
		QUESTIONS.put("城里打擂是挂机里的第几个任务", "d");
		QUESTIONS.put("以下哪个不是鲁长老教导的武学", "d");
		QUESTIONS.put("以下哪些物品不是成长计划第一天可以领取的", "d");
		QUESTIONS.put("包拯在哪一章", "d");
		QUESTIONS.put("张天师在茅山哪个场景", "d");
		QUESTIONS.put("山河藏宝图需要在哪个NPC手里购买", "d");
		QUESTIONS.put("影响你出生的福缘的出生是", "d");
		QUESTIONS.put("张三丰在武当山哪个场景", "d");
		QUESTIONS.put("春秋水色斋需要多少杀气才能进入", "d");
		QUESTIONS.put("论剑中以下哪个不是是晚月庄的技能", "d");
		QUESTIONS.put("大乘佛法有什么效果", "d");
		QUESTIONS.put("正邪任务最多可以完成多少个", "d");
		QUESTIONS.put("高级突破丹多少元宝一颗", "d");
		QUESTIONS.put("清虚道长在哪一章", "d");
		QUESTIONS.put("在战斗界面点击哪个按钮可以进入聊天界面", "d");
		QUESTIONS.put("“鹰记商号”场景是在哪个地图上", "d");
		QUESTIONS.put("改名字在哪改", "d");
		QUESTIONS.put("以下哪个不是在洛阳场景", "d");
//		QUESTIONS.put("青城派的道德经可以提升哪个属性", "d");
		QUESTIONS.put("金项链可以在哪位npc那里获得", "d");
//		QUESTIONS.put("论语在哪购买", "a");
//		QUESTIONS.put("青城派的道德经可以提升哪个属性", "c");
	}

	public AutoQuestionTask(CommandLine cmdline) {
		this.cmdline = cmdline;
	}

	@SuppressWarnings("unchecked")
	@Override
	public void run() {
		Map<String, Object> map = (Map<String, Object>) cmdline.js(
				cmdline.load("get_msgs.js"), "msg_html_page", true);
		if (map == null) {
			return;
		}
		String html = (String) map.get("msg");
		if (html == null) {
			return;
		}
		Matcher m = TITLE_PATTERN.matcher(html);
		if (!m.find()) {
			return;
		}
		int count = Integer.parseInt(m.group(1));
		int total = Integer.parseInt(m.group(2));
		if (html.indexOf("回答正确！") >= 0) {
			System.out.println(" - right!");
			if (count < total) {
				cmdline.sendCmd("question");
			} else {
				System.out.println("finish!");
				cmdline.stopTask(this);
			}
			return;
		}
		if (html.indexOf("回答错误！") >= 0) {
			System.out.println(" - wrong!");
			cmdline.stopTask(this);
			return;
		}
		int i = html.indexOf("</p>") + 4;
		int j = html.indexOf(3, i);
		String question = CommandLine.removeSGR(html.substring(i, j)).trim();
		if (question.endsWith("？") || question.endsWith("?")) {
			question = question.substring(0, question.length() - 1);
		}
		System.out.println(question);
		String answer = QUESTIONS.get(question);
		if (answer == null) {
			System.out.println("answer not found!");
			return;
		}
		System.out.print("answer " + answer);
		cmdline.sendCmd("question " + answer);
	}
}
